In [6]:
import pandas as pd
import seaborn as sns

In [35]:
salary= pd.read_csv("Salary_Data.csv")
salary.tail()
salary["Salary"] = salary["Salary"].fillna(salary["Salary"].mean())

In [36]:
categorical_cols = salary.select_dtypes(include=['object']).columns
print(categorical_cols)

Index(['Gender', 'Education Level', 'Job Title'], dtype='object')

In [42]:
x= salary.drop(columns=["Salary"])
y=salary["Salary"]

x["Gender"]= x["Gender"].map({"Female":0,"Male":1})
x= pd.get_dummies(x, columns=["Job Title"], drop_first=True, dtype=int)

education = {
    "High School": 0,
    "Bachelor's": 1,
    "Bachelor's Degree": 1,
    "Master's": 2,
    "Master's Degree": 2,
    "PhD": 3,
    "phD": 3
}

x["Education Level"] = x["Education Level"].map(education)
x.tail()
x.isnull().sum()

Age                            2
Gender                        16
Education Level                3
Years of Experience            3
Job Title_Accountant           0
                              ..
Job Title_UX Designer          0
Job Title_UX Researcher        0
Job Title_VP of Finance        0
Job Title_VP of Operations     0
Job Title_Web Developer        0
Length: 196, dtype: int64

In [49]:
x["Age"] = x["Age"].fillna(x["Age"].mean())

x["Gender"] = x["Gender"].fillna(x["Gender"].mode()[0])

x["Education Level"] = x["Education Level"].fillna(
    x["Education Level"].mode()[0]
)

x["Years of Experience"] = x["Years of Experience"].fillna(
    x["Years of Experience"].mean()
)

In [50]:
x.isnull().sum()

Age                           0
Gender                        0
Education Level               0
Years of Experience           0
Job Title_Accountant          0
                             ..
Job Title_UX Designer         0
Job Title_UX Researcher       0
Job Title_VP of Finance       0
Job Title_VP of Operations    0
Job Title_Web Developer       0
Length: 196, dtype: int64

In [53]:
# Train Test split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x, y, test_size=0.2, random_state=42)
from sklearn.linear_model import LinearRegression

model =LinearRegression()
model.fit(x_train,y_train)
y_pred = model.predict(x_test)

In [55]:


from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

print("MAE :", mean_absolute_error(y_test, y_pred))
print("MSE :", mean_squared_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R2 :", r2_score(y_test, y_pred))

MAE : 15131.43325218595
MSE : 443438030.29699934
RMSE: 21057.9683326051
R2 : 0.8339612321935311

In [57]:
comparison = pd.DataFrame({
    "Actual Salary": y_test.values,
    "Predicted Salary": y_pred
})

comparison.head(10)

   Actual Salary  Predicted Salary
0       156486.0     186979.753115
1       140000.0     116793.263383
2        80000.0     104884.525595
3        40000.0      40985.789009
4        50000.0      47802.151502
5        95000.0     103718.694313
6        55000.0      72665.379002
7        30000.0      30956.694514
8       160000.0     148671.252356
9       155000.0     121336.383349

In [59]:
salary

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0
...,...,...,...,...,...,...
6699,49.0,Female,PhD,Director of Marketing,20.0,200000.0
6700,32.0,Male,High School,Sales Associate,3.0,50000.0
6701,30.0,Female,Bachelor's Degree,Financial Manager,4.0,55000.0
6702,46.0,Male,Master's Degree,Marketing Manager,14.0,140000.0
6703,26.0,Female,High School,Sales Executive,1.0,35000.0

In [61]:
y_test

2794    156486.0
2233    140000.0
5559     80000.0
6355     40000.0
263      50000.0
          ...
3193     50000.0
2157    185000.0
2202    150000.0
1801    180000.0
2836    171468.0
Name: Salary, Length: 1341, dtype: float64

In [62]:
y_pred

array([186979.75311533, 116793.26338301, 104884.5255955 , ...,
       113715.7244023 , 174399.25265226, 195516.08318499], shape=(1341,))