In [1]:
import pandas as pd
import seaborn as sb

In [50]:
house_data= pd.read_csv("HousePricePrediction.csv")

In [52]:
house_data

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0,856,208500
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0,1262,181500
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0,920,223500
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0,756,140000
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0,1145,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1455,60,RL,7917,Inside,1Fam,5,1999,2000,VinylSd,0,953,175000
1456,1456,20,RL,13175,Inside,1Fam,6,1978,1988,Plywood,163,1542,210000
1457,1457,70,RL,9042,Inside,1Fam,9,1941,2006,CemntBd,0,1152,266500
1458,1458,20,RL,9717,Inside,1Fam,6,1950,1996,MetalSd,1029,1078,142125
1459,1459,20,RL,9937,Inside,1Fam,6,1965,1965,HdBoard,290,1256,147500

In [53]:
X= house_data.drop(columns=["MSZoning","LotConfig", "BldgType","Exterior1st","SalePrice"])
y= house_data["SalePrice"]

In [54]:
y.head()

0    208500
1    181500
2    223500
3    140000
4    250000
Name: SalePrice, dtype: int64

In [55]:
# Train Test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X, y, test_size=0.2, random_state=42)

In [56]:
X_train.head()

,Id,MSSubClass,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF
254,254,20,8400,6,1957,1957,0,1314
1066,1066,60,7837,7,1993,1994,0,799
638,638,30,8777,7,1910,1950,0,796
799,799,50,7200,7,1937,1950,0,731
380,380,50,5000,6,1924,1950,0,1026

In [57]:
X_train["BsmtFinSF2"] = X_train["BsmtFinSF2"].fillna(0)
X_train["TotalBsmtSF"] = X_train["TotalBsmtSF"].fillna(0)

X_test["BsmtFinSF2"] = X_test["BsmtFinSF2"].fillna(0)
X_test["TotalBsmtSF"] = X_test["TotalBsmtSF"].fillna(0)

In [63]:
y_train.head()

254     145000
1066    178000
638      85000
799     175000
380     127000
Name: SalePrice, dtype: int64

In [60]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [65]:
y_pred= model.predict(X_test)
y_pred

array([202557.9374021 , 233620.62893383, 120051.98714356, 134040.35280726,
       263271.0227539 , 127449.81819674, 186181.16276496, 157753.60118982,
       124602.09639799, 142621.77848951, 113476.10189918, 151218.99523931,
       115932.44986158, 247003.18467406, 197295.80982232, 190478.30449889,
       196683.48422666, 189193.45185039, 110146.07255011, 241062.78321246,
       170374.88570578, 198356.31967826, 191416.91209722, 173206.38788033,
       231725.43526673, 209131.11365407, 236915.33921068, 130252.93645157,
       196582.04197476, 237159.60189715, 117687.61232551, 210615.52014226,
       215265.79562956, 143187.59054908, 261730.16884636, 165664.64614092,
       157704.00844856, 196667.88814434, 235795.62958066,  66883.8650627 ,
       107833.51848756, 197559.17116438, 150116.43011055, 295281.68156324,
       144092.2503778 ,  83683.07461516, 128169.53782968, 157409.64575552,
       273629.90177903, 134603.1080979 , 125944.91736628, 210552.38688086,
       116953.34271785, 212385.24519968, 196182.84126517, 265841.70907807,
       174629.94713716, 188160.59228909, 167152.82543625, 116161.4291717 ,
        80964.70036843, 180425.02131133, 221292.86730611, 256647.40077972,
       272928.39753314, 202120.41534498, 110126.75161905, 247188.09108399,
       189618.33051564, 180092.61758481,  98283.19918269, 139842.91653232,
       136115.97357928,  51259.91307056, 318377.47626115, 215924.07513364,
       229914.62502768, 218789.5140718 , 145271.08906059, 152845.50668495,
       167817.25903191,  89955.14443315, 146858.40711742, 114600.38276183,
       156630.87748927, 158696.99559954, 221264.63854634, 214597.52838436,
       196343.87195404, 195367.37548778, 192780.02295101, 137406.82768878,
       171726.11058676, 190808.27944617, 215674.77017743, 234880.3761576 ,
       169246.42882024, 178576.66696463, 247029.47549443, 178078.67165262,
       198137.40235183, 198996.9580622 , 262104.88634541, 161504.09430084,
       209708.19457004, 147643.05173747, 194907.16935247, 236044.71637106,
       193541.64079969, 163505.62957707,  50963.53674882, 171310.35836971,
       204958.97004057, 168555.89058475, 208191.78131563, 152847.09668469,
       174459.70207548, 147924.39809182,  99153.69668329, 360830.49891958,
       174549.58548131, 195808.44387027, 193071.05395616, 160374.71549367,
       215426.97505614, 148196.1991747 , 199957.12351628, 111822.96217534,
       217594.28058342, 157360.92543908, 191882.71616943, 276615.90255324,
       192756.06890075,  90433.41335408,  77693.55654438, 267143.64656904,
       270048.45064806, 159554.65226185, 252085.44932626, 321551.76091585,
       237744.26127339, 185732.58808375, 162243.55081392, 126681.521286  ,
       175843.49248811, 144987.59461869, 168333.65290986, 242809.62751351,
       188340.83611561,  84101.71672088,  91909.30009137, 126276.90327226,
       245260.6946565 , 156495.01205394, 107039.19442095, 159312.13547005,
       172717.95023683, 162838.31919135, 131940.1425572 , 159963.03551371,
       231311.60854011, 177200.05813136, 260778.49432494, 198650.84528087,
       114159.08319369, 199376.48477421, 196220.47437424, 249909.68508301,
       293091.82277952, 154572.87856606, 276590.16750164, 130312.22109696,
       111811.84592026, 142426.30774311, 250760.27820653,  72196.95501203,
       100303.31832289, 206200.44342575, 150646.74831559, 183072.10749218,
       216054.50229326,  96486.22027292, 164850.38840324, 148492.02570558,
       214324.64094522,  87815.12338779, 251427.61903927, 236415.37596776,
       239918.40518044, 122694.58938743, 139891.03528509, 133129.5735779 ,
       114958.98246173, 184418.61982257, 232545.14579355, 179717.37420017,
       225907.1544005 ,  79329.92761648, 197991.62586393,  96006.91132068,
       273402.39063319, 193136.26879372, 141709.34820581, 235329.10838075,
       230584.71226737, 144915.80455874, 206877.5832463 , 161347.53620718,
       161472.76216314, 142287.30545708, 172469.24452534, 141830.12194442,
       137267.38039472, 180486.72010577, 228946.46206923, 255021.37594411,
       229457.99569013, 152927.83422147, 132467.90064597,  98874.28356275,
       158175.40313723, 236115.63975937, 206202.6929263 , 101713.20929681,
       246525.23756019, 205163.13119461,  81637.38550402, 146867.51476327,
       184124.36828854,  99133.26037477, 114534.82323296, 170174.72229621,
       134589.91106521, 161263.0053075 , 186163.1185466 , 143588.18957996,
       224808.28172803, 194189.81711905, 204042.17211531, 167500.40305675,
       149571.90456735, 182926.43400084, 213193.67912626, 247624.76473111,
       163828.69619732, 164647.84709641, 155456.88637449, 200926.29246041,
       179200.07434141, 103537.60453962, 206442.61620465, 149061.8951038 ,
       142338.94123498,  88840.63351567, 160842.40175006, 172279.36898173,
       159785.43565939, 142902.61940522, 172208.3736335 , 214905.77745141,
       285404.71996801, 191083.10397899, 150492.97154004, 230496.3123809 ,
       265742.12984093, 212925.73232331, 215495.32836984, 195914.99756025,
       137261.34288175, 157564.47127118, 295681.88005908, 216842.61024627,
       220326.45359958, 115075.8522018 ,  76440.37337303, 162845.53959973,
       205033.80072674, 279230.57507685, 252014.24991661, 127784.4435917 ,
       207752.12205328, 140801.23395379, 194877.44461591, 161125.77413579,
       266626.18627536, 201985.44082148, 205351.29109603, 164767.31696434,
       256685.61304714, 190273.45626308, 105910.15119776, 157498.15918877])

In [67]:
y_test

892     154500
1105    325000
413     115000
522     159000
1036    315500
         ...
479      89471
1361    260000
802     189000
651     108000
722     124500
Name: SalePrice, Length: 292, dtype: int64

In [68]:
from sklearn.metrics import r2_score
r2= r2_score(y_test, y_pred)
print("r-squared:", r2)

r-squared: 0.5749178852345285