In [3]:
 import requests

In [4]:
URL="https://stephen-king-api.onrender.com/api/books"
res= requests.get(URL)

In [5]:
json_data=res.json()

In [6]:
import pandas as pd
df=pd.json_normalize(json_data["data"])

In [7]:
df=df[['id','Title','Year']]

In [8]:
df

    id          Title  Year
0    1         Carrie  1974
1    2    Salem's Lot  1975
2    3    The Shining  1977
3    4           Rage  1977
4    5      The Stand  1978
..  ..            ...   ...
58  59   The Outsider  2018
59  60      Elevation  2018
60  61  The Institute  2019
61  62          Later  2021
62  63  Billy Summers  2021

[63 rows x 3 columns]

In [9]:
headers={
    "User-Agent": "Chrome"  #requst will sended as chrome
}
URL="https://www.scrapethissite.com/pages/simple/"
res= requests.get(URL,headers=headers)

In [10]:


if (res.status_code==200):
    print(res)
with open("data1.html","w",encoding="utf-8") as f:
    f.write(res.text)

<Response [200]>

In [3]:
#beutiful soup
from bs4 import BeautifulSoup

with open("data1.html","r") as f:
    html_content=f.read()
soup=BeautifulSoup(html_content,"lxml")

In [15]:
soup.find("h1") # find the first occurence

<h1>
                            Countries of the World: A Simple Example
                            <small>250 items</small>
</h1>

In [35]:
all_h3=soup.find_all("h3") #give all the occurence
all_countries=[]

for h3 in all_h3:
    name=(h3.get_text(strip=True)) #give the content of all the tag check it
    #remove the spaces strip=true
    population=(h3.find_next("div").select("span.country-population")[0].get_text(strip=True)) #find the next class 
    all_countries.append([name,population])

In [40]:

import pandas as pd
pd.DataFrame(all_countries,columns=["Name","Population"])

                     Name Population
0                 Andorra      84000
1    United Arab Emirates    4975593
2             Afghanistan   29121286
3     Antigua and Barbuda      86754
4                Anguilla      13254
..                    ...        ...
245                 Yemen   23495361
246               Mayotte     159042
247          South Africa   49000000
248                Zambia   13460305
249              Zimbabwe   11651858

[250 rows x 2 columns]